# Generated by Django 5.2.1 on 2025-07-08 22:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Palavra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=50, verbose_name='Texto da palavra')),
                ('dica', models.CharField(blank=True, max_length=100, null=True, verbose_name='Dica')),
                ('texto_auxiliar', models.TextField(blank=True, null=True, verbose_name='Texto auxiliar')),
            ],
            options={
                'verbose_name': 'Palavra',
                'verbose_name_plural': 'Palavras',
            },
        ),
        migrations.CreateModel(
            name='Jogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acertos', models.IntegerField(default=0, verbose_name='Acertos')),
                ('erros', models.IntegerField(default=0, verbose_name='Erros')),
                ('status', models.CharField(choices=[('em_andamento', 'Em andamento'), ('ganhou', 'Ganhou'), ('perdeu', 'Perdeu')], default='em_andamento', max_length=20, verbose_name='Status')),
                ('data', models.DateTimeField(auto_now_add=True, verbose_name='Data')),
                ('jogador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Jogador')),
                ('palavra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jogo.palavra', verbose_name='Palavra')),
            ],
            options={
                'verbose_name': 'Jogo',
                'verbose_name_plural': 'Jogos',
            },
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eh_professor', models.BooleanField(default=False, verbose_name='É professor')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Perfil',
                'verbose_name_plural': 'Perfis',
            },
        ),
        migrations.CreateModel(
            name='Tema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome do tema')),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temas_criados', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
            ],
            options={
                'verbose_name': 'Tema',
                'verbose_name_plural': 'Temas',
            },
        ),
        migrations.AddField(
            model_name='palavra',
            name='tema',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='palavras', to='jogo.tema', verbose_name='Tema'),
        ),
    ]
